companies = ["'wichcraft",
            '1-800-PetMeds',
            '1871',
            '33Across',
            '360 Live Media',
            '540',
            '8020 Consulting',
            'AAA Club Alliance',
            'AOL',
            'AT&T',
            'AbelsonTaylor',
            'Accenture',
            'Accolade',
            'Achievement First',
            'Acquirent',
            'AddThis',
            'Adlib Software',
            'Affect',
            'Affectiva',
            'Aflac',
            'Agile',
            'Airbnb',
            'Akilah Group',
            'Alcon',
            'Allstate',
            'AlphaSights',
            'Alphaserve Technologies',
            'Altarum',
            'American Association For The Advancement of Science',
            'Amplify',
            'Andela',
            'Anne Lewis Strategies',
            'AppFolio',
            'AppLift',
            'AppNexus',
            'Appian',
            'Area 1 Security',
            'Argen Corporation',
            'Armani',
            'Arrow Electronics',
            'Asana',
            'Ascendum',
            'Asurion',
            'Atlassian',
            'Austin Film Festival',
            'Autodesk',
            'Axial',
            'Axiom',
            'BAE Systems',
            'Backcountry.com',
            'Bai Brands',
            'Balsam Brands',
            'Banfield Pet Hospital',
            'Bankrate.com',
            'Base CRM',
            'Beautycounter',
            'Beepi',
            'Belly',
            'Best Made Co',
            'Better Mortgage',
            'BetterCloud',
            'Betterment',
            'Big Fish Games',
            'Billtrust',
            'Bionic',
            'Birchbox',
            'Bitly',
            'Bizzabo',
            'Black Mountain Systems',
            'Blackbaud',
            'Bleacher Report',
            'Blinds.com',
            'Bloomberg',
            'Bluebeam',
            'Bluewolf',
            'BodenPR',
            'Bonobos',
            'Book Of The Month',
            'Bounce Exchange',
            'Box',
            'Bozzuto',
            'Braintree',
            'BrandEQ',
            'Bridgespan',
            'Bright Pink',
            'Brightbox',
            'Broadridge',
            'Bunkhouse',
            'CA Technologies',
            'CARFAX',
            'CEB',
            'COPE Health Solutions',
            'COUNTRY Financial',
            'Call Box (formerly Century Interactive)',
            'Cansel',
            'Canvas',
            'Capital One',
            'Captivate',
            'Captora',
            'CarMax',
            'Cardlytics',
            'CareerVillage.org',
            'Cargurus',
            'Cello Health Insight',
            'Centerline Digital',
            'CertainTeed',
            'Ceterus',
            'Champion Realty',
            'Chartbeat',
            'Chicago Cubs',
            'Circa Healthcare',
            'Citizen Schools',
            'City of Hope',
            'City of Houston',
            'ClaimTrak',
            'Clara',
            'Clarabridge',
            'ClearSlide',
            'Clearlink',
            'Cleveland Research Company',
            'Client Resources Inc.',
            'CloudPassage',
            'Cloudera',
            'Codeup',
            'Cogo Labs',
            'Collective Health',
            'Comcast',
            'CommonBond',
            'Condé Nast',
            'Consumers Credit Union',
            'Contactually',
            'ContextMedia',
            'Continuum Analytics',
            'Continuum Managed Services',
            'Convene',
            'Conversant',
            'Core Digital Media',
            'Cornerstone OnDemand',
            'Cortina Productions',
            'Corvirtus',
            'Counsyl',
            'CourseHorse',
            'Cox Enterprises',
            'Credit Karma',
            'CreditCards.com',
            'Cree',
            'CrowdTwist',
            'Curacao',
            'Curalate',
            'DAQRI',
            'DMC Atlanta',
            'DX Marketing',
            'Daon',
            'Data Communications Management',
            'DataSift',
            'Datadog',
            'DealerSocket',
            'DecisionDesk',
            'Deloitte',
            'Department of Labor',
            'Devmountain',
            'Dex Media',
            'Dextro',
            'Dia&Co',
            'Digital Air Strike',
            'Digital Trends',
            'DigitalOcean',
            'Discovery',
            'Distractify',
            'Ditto',
            'Docler Media',
            'DogVacay',
            'Dogfish Head',
            'Dolby',
            'Dormify',
            'Double Robotics',
            'Dow Jones',
            'DriveTime',
            'Dropbox',
            'Duarte',
            'Dun & Bradstreet',
            'Dyn',
            'EF Education First',
            'Earnest Research',
            'Ebates',
            'Edmodo',
            'Education Pioneers',
            'Elastic Path',
            'Elevation Church',
            'Encyclopædia Britannica',
            'Engine Room Technology',
            'Entrepreneurs’ Organization',
            'Epsilon',
            'Esri',
            'Euclid Analytics',
            'Evantage',
            'Eventbrite',
            'FDM Group',
            'FTD Companies',
            'FabFitFun',
            'Facebook',
            'Factual',
            'Farmigo',
            'Fetch Robotics',
            'Financial Finesse',
            'First Look Media',
            'FiscalNote',
            'FiveStars',
            'Fiverr',
            'Flickr',
            'Fluxx',
            'Fortegra',
            'Framebridge',
            'FremantleMedia North America',
            'Fresh Digital Group',
            'Freshbooks',
            'Frontline Education',
            'Fueled',
            'Fullscreen Media',
            'Function1',
            'Fundbox',
            'Funding Circle',
            'G5',
            'GLG',
            'Galileo',
            'Gallup',
            'Gannett',
            'Gap Inc.',
            'Geico',
            'General Assembly',
            'Genesys',
            'Gigwalk',
            'GlaxoSmithKline',
            'GlobalGiving',
            'GoHealth',
            'Goldman Sachs',
            'Good Apple Digital',
            'Good Sports',
            'Goodwill',
            'Goodwin Procter',
            'Goose Island Brewery',
            'Goosehead Insurance',
            'Grafik',
            'GrandLife Hotels',
            'Grasshopper',
            'Gravity',
            'Greatist',
            'Group Publishing',
            'GrubHub',
            'Guggenheim Partners',
            'HBO',
            'HBO DIGITAL & SOCIAL MEDIA FELLOWSHIP PROGRAM',
            'HED',
            'HP',
            'HZDG',
            'Handy',
            'Harwood International',
            'HealthcareSource',
            'Hearst Digital Media',
            'Hearst Media Services',
            'Heartland Alliance',
            'Hearts & Science',
            'HelloSign',
            'Hightower',
            'Hirevue',
            'HomeAdvisor',
            'HomeAway',
            'Homesuite',
            'Hometeam',
            'Horizon Group USA',
            'HotelTonight',
            'Houston-The City With No Limits',
            'Houzz',
            'Hudl',
            'Huge',
            'Hypertherm',
            'IEX Group',
            'Ibotta',
            'IgnitionOne',
            'Illumio',
            'Imagitas',
            'Imgur',
            'InMobi',
            'Indagare',
            'Influenster',
            'InfoCision',
            'InsPro Technologies',
            'Insight Consulting Group',
            'Insikt',
            'Insomniac Games',
            'Inspirato',
            'Integrative Nutrition',
            'Intercom',
            'Ironhack',
            'JAMF Software',
            'JDI',
            'JINX',
            'Jive',
            'Johns Hopkins Applied Physics Laboratory',
            'Jumpcut',
            'KDM Engineering',
            'KIND Healthy Snacks',
            'KPMG',
            'Kabam',
            'Kargo',
            'Karma',
            'Kasasa',
            'King Arthur Flour',
            'Kiva',
            'Knot Standard',
            'Korn Ferry',
            'L2',
            'LISI',
            'LRN',
            'Label Insight',
            'Launchmetrics',
            'Leanplum',
            'LegalZoom',
            'Lending Club',
            'Levatas',
            'LevelUp',
            'Lever',
            'Lighthouse Labs',
            'Lincoln Center',
            'Lithium',
            'LivePerson',
            'LiveRamp',
            'Livefyre',
            'Lytx',
            'M Financial Group',
            'MBI',
            'MD Insider',
            'MDA',
            'MM.LaFleur',
            'MWH',
            'Magnetic',
            'Magoosh',
            'MailChimp',
            'Main Street Hub',
            'MakerBot',
            'MakerSquare',
            'Margot Elena Companies and Collections',
            'Marriott International',
            'Mashable',
            'Maven Wave',
            'McKinsey',
            'MealPal',
            'MedStar National Rehabilitation Network',
            'MedXM',
            'Medallia',
            'MediaRadar',
            'Meltwater',
            'Mental Health Center of Denver',
            'Mercedes-Benz Research & Development North America',
            'Method',
            'Mohawk Industries',
            'Moz',
            'MuleSoft',
            'Museum of Contemporary Art',
            'NAS Insurance',
            'NFL',
            'NPR',
            'National Aquarium',
            'National Corporate Housing',
            'Nestio',
            'Networx',
            'NeueHouse',
            'New York Life Technology',
            'NewWave Technologies',
            'NewsCred',
            'Newsela',
            'NextCapital',
            'Nextdoor',
            'Nextiva',
            'Nexus',
            'Ninthlink',
            'Nordson',
            'North American Power',
            'Northrop Grumman',
            'O3B Networks',
            'Oak Mortgage',
            'Odyssey',
            'Odyssey Information Services',
            'OfferUp',
            'Ogilvy',
            'Omnigon',
            'One Acre Fund',
            'One Month',
            'OpenMarket',
            'Oprah Winfrey Network',
            'OptionsCity',
            'Optoro',
            'OutboundEngine',
            'Outbrain',
            'Outdoor Voices',
            'Owens & Minor',
            'Owens Corning',
            'OwnLocal',
            'PEAK6 Investments',
            'POLITICO',
            'PVH',
            'Pabst Brewing Company',
            'Pactiv',
            'Panda Restaurant Group',
            'Pandora',
            'Payscape',
            'Peanut Labs',
            'Peloton Cycle',
            'Penske Motor Group',
            'Pep',
            'Perfect Sense',
            'Periscope Data',
            'Persado',
            'Phase One',
            'Philips',
            'Phoenix Energy',
            'Pinsight Media+',
            'Pinterest',
            'PivotDesk',
            'Placemeter',
            'Plum Organics',
            'Polaris',
            'Prezi',
            'ProQuest',
            'Progressive Insurance',
            'Prosper Marketplace',
            'Public Outreach',
            'PulsePoint',
            'Pulte Mortgage',
            'Pure Storage',
            'PureWow',
            'Quantcast',
            'R2C Group',
            'REVOLT',
            'RXBAR',
            'Radius',
            'Raffa',
            'Rain Bird',
            'Rainforest QA',
            'ReadyTalk',
            'Recombine',
            'Red Ventures',
            'Redbubble',
            'Redfin',
            'Reebok',
            'Reformation',
            'Relias Learning',
            'Remix',
            'RepEquity',
            'Response Mine',
            'Return Path',
            'Revana Digital',
            'Revcontent',
            'Ring',
            'Riviera',
            'Roblox',
            'Robly Email Marketing',
            'Rocket Games',
            'Rocksauce',
            'Rover',
            'Rubicon Global',
            'Rubicon Project',
            'SXSW',
            'Sailthru',
            'Saint-Gobain Performance Plastics',
            'San Diego Zoo Global',
            'San Francisco Chronicle',
            'Sandbox',
            'ScaleFactor',
            'Schoology',
            'Screen Pilot',
            'Scribd',
            'Sears Holdings',
            'SendGrid',
            'Sensibill',
            'ServiceTitan',
            'Sestra Systems',
            'Shopify',
            'Shutterstock',
            'Signpost',
            'Simplicity Consulting',
            'Sinclair Broadcast Group',
            "Sir Kensington's",
            'SiriusDecisions',
            'Skillshare',
            'Slack',
            'SmartBear',
            'SmartBrief',
            'SmashBoxCosmetics',
            'Sneak Attack Media',
            'SoFi',
            'Society for the Promotion of Japanese Animation',
            'Southern Management Corporation',
            'Sovrn',
            'Spanx',
            'Spencer Stuart',
            'Spherical',
            'Spiceworks',
            'Spredfast',
            'Squarespace',
            'Stack Overflow',
            'StackCommerce',
            'StellaService',
            'Stockpile',
            'Strategic Mobility Group',
            'Stylight',
            'Success Academy Charter Schools',
            'Summit Information Resources',
            'Swirl',
            'Swoon Group',
            'Symphony',
            'Synapse',
            'Synaptics',
            'T-Mobile',
            'TAMKO',
            'TED',
            'TNTP',
            'TYRA Beauty',
            'Taboola',
            'Take-Two Interactive Software',
            'TapInfluence',
            'Tapingo',
            'Target',
            'Tasting Table',
            'Teach For America',
            'Technology at Gap Inc.',
            'Ted Todd',
            'The Avenue West',
            'The Broad Residency in Urban Education',
            'The Honest Company',
            'The Muse',
            'The Nerdery',
            'The New York Foundling',
            'The Predictive Index',
            'The Select Group',
            'The Trium Group',
            'The Wall Street Journal',
            'The Washington Redskins',
            'ThoughtWorks',
            'Thoughtspot',
            'Thumbtack',
            'Tile',
            'Tillster',
            'Tilt',
            'TomTom',
            'TrackMaven',
            'TransUnion',
            'TravelClick',
            'Tresta',
            'Triose',
            'TripAdvisor',
            'TripleLift',
            'Tripwire',
            'Trumaker',
            'Trustpilot',
            'Trustwave',
            'TubeMogul',
            'Twilio',
            'Twitch',
            'U.S. BMW Group Companies',
            'USEED',
            'Uber',
            'Ultimate Software',
            'Understory',
            'Unilever',
            'Upwork',
            'VMware',
            'VSA Partners',
            'VSCO',
            'Vanguard',
            'Veeva',
            'Venmo',
            'Venture For America',
            'Vera Bradley',
            'Verisk Insurance Solutions',
            'VideoBlocks',
            'VigLink',
            'Virgin Mobile',
            'Virid',
            'Virool',
            'Volusion',
            'Voxy',
            'Vynamic',
            'W by Worth',
            'W4',
            'WAXIE Sanitary Supply',
            'Wallaby Financial',
            'Warby Parker',
            'Washington REIT',
            'WeWork',
            'Wealthfront',
            'Wellness Connection of Maine',
            'Wells Fargo',
            'When I Work',
            'Work Better',
            'Work Market',
            'World Wildlife Fund',
            'Worldwide101',
            'YES Prep',
            'YETI Coolers',
            'YETI Custom Shop',
            'Yale New Haven Hospital',
            'Yext',
            'Yodle',
            'Zappos',
            'ZestFinance',
            'Ziprealty',
            'Zoosk',
            'charity: water',
            'd’aprile properties',
            'eMarketer',
            'iCIMS',
            'iMedicare',
            'iProspect',
            'kWantera',
            'mobileforming',
            'mywedding.com',
            'natrel',
            'priceline.com']